// remote-react-app/src/components/CsvViewer.tsx
import { useState, useRef, useEffect } from 'react';
import Papa from 'papaparse';

interface CsvData {
  data: string[][];
  headers: string[];
}

const CsvViewer = () => {
  const [csvData, setCsvData] = useState<CsvData | null>(null);
  const [fileName, setFileName] = useState<string>('');
  const fileInputRef = useRef<HTMLInputElement>(null);

  const handleFileUpload = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;

    setFileName(file.name);

    Papa.parse(file, {
      complete: (result) => {
        // Extract headers from the first row
        const headers = result.data[0] as string[];
        // Remove the header row from the data
        const data = result.data.slice(1) as string[][];
        
        setCsvData({ data, headers });
      },
      header: false,
    });
  };

  // Expose the CSV data to the parent application
  useEffect(() => {
    if (csvData) {
      // @ts-ignore - This is for Module Federation communication
      window.reactCsvData = {
        data: csvData.data,
        headers: csvData.headers,
        fileName: fileName,
        source: 'react'
      };
    }
  }, [csvData, fileName]);

  return (
    <div className="csv-viewer">
      <h2>React CSV Viewer</h2>
      <div className="file-upload">
        <input
          type="file"
          accept=".csv"
          onChange={handleFileUpload}
          ref={fileInputRef}
          style={{ display: 'none' }}
        />
        <button onClick={() => fileInputRef.current?.click()}>
          Select CSV File
        </button>
        {fileName && <span className="file-name">{fileName}</span>}
      </div>

      {csvData && (
        <div className="csv-preview">
          <h3>Preview:</h3>
          <table>
            <thead>
              <tr>
                {csvData.headers.map((header, index) => (
                  <th key={index}>{header}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {csvData.data.slice(0, 5).map((row, rowIndex) => (
                <tr key={rowIndex}>
                  {row.map((cell, cellIndex) => (
                    <td key={cellIndex}>{cell}</td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
          {csvData.data.length > 5 && (
            <p>Showing 5 of {csvData.data.length} rows</p>
          )}
        </div>
      )}
    </div>
  );
};

export default CsvViewer;

// remote-angular-app/src/app/csv-viewer/csv-viewer.component.ts
import { Component, ElementRef, ViewChild } from '@angular/core';
import * as Papa from 'papaparse';

interface CsvData {
  data: string[][];
  headers: string[];
}

@Component({
  selector: 'app-csv-viewer',
  templateUrl: './csv-viewer.component.html',
  styleUrls: ['./csv-viewer.component.scss']
})
export class CsvViewerComponent {
  @ViewChild('fileInput') fileInput!: ElementRef;
  
  csvData: CsvData | null = null;
  fileName: string = '';

  constructor() {}

  openFileSelector(): void {
    this.fileInput.nativeElement.click();
  }

  handleFileUpload(event: Event): void {
    const input = event.target as HTMLInputElement;
    const file = input.files?.[0];
    
    if (!file) return;

    this.fileName = file.name;

    Papa.parse(file, {
      complete: (result) => {
        // Extract headers from the first row
        const headers = result.data[0] as string[];
        // Remove the header row from the data
        const data = result.data.slice(1) as string[][];
        
        this.csvData = { data, headers };
        
        // Expose the CSV data to the parent application
        (window as any).angularCsvData = {
          data: this.csvData.data,
          headers: this.csvData.headers,
          fileName: this.fileName,
          source: 'angular'
        };
      },
      header: false,
    });
  }
}
<div class="csv-viewer">
    <h2>Angular CSV Viewer</h2>
    <div class="file-upload">
      <input
        type="file"
        accept=".csv"
        (change)="handleFileUpload($event)"
        #fileInput
        style="display: none"
      />
      <button (click)="openFileSelector()">
        Select CSV File
      </button>
      <span class="file-name" *ngIf="fileName">{{ fileName }}</span>
    </div>
  
    <div class="csv-preview" *ngIf="csvData">
      <h3>Preview:</h3>
      <table>
        <thead>
          <tr>
            <th *ngFor="let header of csvData.headers; let i = index">{{ header }}</th>
          </tr>
        </thead>
        <tbody>
          <tr *ngFor="let row of csvData.data.slice(0, 5); let rowIndex = index">
            <td *ngFor="let cell of row; let cellIndex = index">{{ cell }}</td>
          </tr>
        </tbody>
      </table>
      <p *ngIf="csvData.data.length > 5">Showing 5 of {{ csvData.data.length }} rows</p>
    </div>
  </div>
